apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: multitalent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/hsmg777/multitalent_backend_tita/api:44d50808c87e23dd4ac74e2ad6322d236de9bd15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          command: ["gunicorn"]
          args:
            [
              "-w", "2",
              "-k", "gthread",
              "--threads", "8",
              "--timeout", "60",
              "-b", "0.0.0.0:8000",
              "app.wsgi:app"
            ]
          env:
            - name: FLASK_ENV
              value: "production"
            - name: LD_SDK_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: LD_SDK_KEY


