apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: multitalent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: hsmg7777/multitalent-backend-api:prod   
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          command: ["gunicorn"]
          args:
            [
              "-w", "2",
              "-k", "gthread",
              "--threads", "8",
              "--timeout", "60",
              "-b", "0.0.0.0:8000",
              "app.wsgi:app"
            ]
          env:
            # EJEMPLOS: aqu√≠ luego copias variables de tu .env
            - name: FLASK_ENV
              value: "production"
            # - name: DATABASE_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: api-secrets
            #       key: DATABASE_URL
